[settings]
default_view_mode = small_icons
show_hidden_files = false
show_file_extensions = true
show_used_space = false
show_space_bar = false
sort_field = name
sort_ascending = true
theme = dark
icon_theme = files-basic
font_pixel_size = 16
info_pane_open = false
use_system_default_opener = true
group_by = none
detail_column_modified = true
detail_column_size = true
detail_column_filetype = true
detail_column_created = false
detail_column_permissions = false

[filetypes]
adb = text/x-ada
ads = text/x-ada
docx = application/vnd.openxmlformats-officedocument.wordprocessingml.document
gz = application/gzip
jpeg = image/jpeg
jpg = image/jpeg
json = application/json
md = text/markdown
mp3 = audio/mpeg
mp4 = video/mp4
pdf = application/pdf
png = image/png
tar = application/x-tar
tar.gz = application/gzip-tar
txt = text/plain
wav = audio/wav
xlsx = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
xml = application/xml
zip = application/zip

[icons]
application/gzip = unknown
application/gzip-tar = unknown
application/json = text
application/octet-stream = unknown
application/pdf = text
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet = text
application/vnd.openxmlformats-officedocument.wordprocessingml.document = text
application/x-executable = executable
application/x-tar = unknown
application/xml = text
application/zip = unknown
audio/mpeg = unknown
audio/wav = unknown
image/jpeg = image
image/png = image
inode/directory = folder
inode/symlink = link
text/markdown = text
text/plain = text
text/x-ada = ada
video/mp4 = unknown

[open-actions]
text/plain = xdg-open {path}

